function [T, notesText] = poemAnalysis_preProcess_redcap(spreadSheetName)
% Cleans and organizes data from a raw POEM responses spreadsheet
%
% Syntax:
%  [T, notesText] = poemAnalysis_preProcess_redcap(spreadSheetName)
%
% Description:
%   Loads csv file into which Redcap migraine assessment data has been
%   stored. Cleans and organizes the data
%
% Inputs:
%   spreadSheetName       - String variable with the full path to the csv file
%
% Outputs:
%   T                     - The table
%   notesText             - A cell array with notes regarding the table conversion
%

%% Parse input and define variables
p = inputParser;

% required input
p.addRequired('spreadSheetName',@ischar);

% parse
p.parse(spreadSheetName)


%% Hardcoded variables and housekeeping
notesText = cellstr(spreadSheetName);

% This is the format of time stamps returned by Redcap
% dateTimeFormat = 'yyyy-MM-dd HH:mm:SS';

%% Read in the table. Suppress some routine warnings.
orig_state = warning;
warning('off','MATLAB:table:ModifiedAndSavedVarnames');
warning('off','MATLAB:table:ModifiedVarnames');
T = readtable(spreadSheetName,'DatetimeType','text');
warning(orig_state);

%% Stick the question text into the UserData field of the Table
T.Properties.UserData.QuestionText = table2cell(T(1,:));

% select only completed participants
T = T(1:143,:);

%% Clean and Sanity check the table
% Keep Time point 1 when data were collected (Headache Substudy), remove Administrative, and Time points 2 and 3
T = T(categorical(T.EventName)=='Time point 1',[1 6:133]); % select POEM only
T.RecordID_ = categorical(T.RecordID_);

% Change question text variables to categorical
T.AreYourEyesSensitiveToLight_ = categorical(T.AreYourEyesSensitiveToLight_);
T.DoYouGetHeadaches_ = categorical(T.DoYouGetHeadaches_);
T.HaveYouEverHadAHeadache_ = categorical(T.HaveYouEverHadAHeadache_);
T.HaveYouEverHadAHeadacheThatWasNOTCausedByAHeadInjuryOrIllnessLi = categorical(T.HaveYouEverHadAHeadacheThatWasNOTCausedByAHeadInjuryOrIllnessLi);
T.DoYouGetHeadachesThatAreNOTCausedByAHeadInjuryOrIllnessLikeTheC = categorical(T.DoYouGetHeadachesThatAreNOTCausedByAHeadInjuryOrIllnessLikeTheC);
T.DoYourHeadachesEverLastMoreThanTwoHours_ = categorical(T.DoYourHeadachesEverLastMoreThanTwoHours_);
T.HaveYouEverHadEpisodesOfDiscomfort_Pressure_OrPainAroundYourEye = categorical(T.HaveYouEverHadEpisodesOfDiscomfort_Pressure_OrPainAroundYourEye);
T.HowWouldYouDescribeThisPainOrDiscomfort_ = categorical(T.HowWouldYouDescribeThisPainOrDiscomfort_);
T.HowIntenseWouldYouRateThisPainOrDiscomfort_ = categorical(T.HowIntenseWouldYouRateThisPainOrDiscomfort_);
T.DuringTheseEpisodes_DoYouEverExperienceTheFollowingSymptoms__ch = categorical(T.DuringTheseEpisodes_DoYouEverExperienceTheFollowingSymptoms__ch);
T.DuringTheseEpisodes_DoYouEverExperienceTheFollowingSymptoms___1 = categorical(T.DuringTheseEpisodes_DoYouEverExperienceTheFollowingSymptoms___1);
T.DuringTheseEpisodes_DoYouEverExperienceTheFollowingSymptoms___2 = categorical(T.DuringTheseEpisodes_DoYouEverExperienceTheFollowingSymptoms___2);
T.DuringTheseEpisodes_DoYouEverExperienceTheFollowingSymptoms___3 = categorical(T.DuringTheseEpisodes_DoYouEverExperienceTheFollowingSymptoms___3);
T.HaveYouEverTakenMedicationToMakeThePainOrDiscomfortFeelBetter_ = categorical(T.HaveYouEverTakenMedicationToMakeThePainOrDiscomfortFeelBetter_);
T.HowManyTimesInYourLifeHasThisPainOrDiscomfortHappened_ = categorical(T.HowManyTimesInYourLifeHasThisPainOrDiscomfortHappened_);
T.WhenIsTheLastTimeYouFeltThisPainOrDiscomfort_ = categorical(T.WhenIsTheLastTimeYouFeltThisPainOrDiscomfort_);
T.DoYouUsuallyGetHeadachesAroundYourMenstrualPeriods_ = categorical(T.DoYouUsuallyGetHeadachesAroundYourMenstrualPeriods_);
T.ForYouWORSTTypeOfHeadache_DoAnyOfTheFollowingStatementsDescribe = categorical(T.ForYouWORSTTypeOfHeadache_DoAnyOfTheFollowingStatementsDescribe);
T.ForYouWORSTTypeOfHeadache_DoAnyOfTheFollowingStatementsDescri_1 = categorical(T.ForYouWORSTTypeOfHeadache_DoAnyOfTheFollowingStatementsDescri_1);
T.ForYouWORSTTypeOfHeadache_DoAnyOfTheFollowingStatementsDescri_2 = categorical(T.ForYouWORSTTypeOfHeadache_DoAnyOfTheFollowingStatementsDescri_2);
T.ForYouWORSTTypeOfHeadache_DoAnyOfTheFollowingStatementsDescri_3 = categorical(T.ForYouWORSTTypeOfHeadache_DoAnyOfTheFollowingStatementsDescri_3);
T.ForYouWORSTTypeOfHeadache_DoAnyOfTheFollowingStatementsDescri_4 = categorical(T.ForYouWORSTTypeOfHeadache_DoAnyOfTheFollowingStatementsDescri_4);
T.DuringYourWORSTTypeOfHeadaches_DoYouEverExperienceTheFollowingS = categorical(T.DuringYourWORSTTypeOfHeadaches_DoYouEverExperienceTheFollowingS);
T.DuringYourWORSTTypeOfHeadaches_DoYouEverExperienceTheFollowin_1 = categorical(T.DuringYourWORSTTypeOfHeadaches_DoYouEverExperienceTheFollowin_1);
T.DuringYourWORSTTypeOfHeadaches_DoYouEverExperienceTheFollowin_2 = categorical(T.DuringYourWORSTTypeOfHeadaches_DoYouEverExperienceTheFollowin_2);
T.DuringYourWORSTTypeOfHeadaches_DoYouEverExperienceTheFollowin_3 = categorical(T.DuringYourWORSTTypeOfHeadaches_DoYouEverExperienceTheFollowin_3);
T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Please = categorical(T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Please);
T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_1 = categorical(T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_1);
T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_2 = categorical(T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_2);
T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_3 = categorical(T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_3);
T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_4 = categorical(T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_4);
T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_5 = categorical(T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_5);
T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_6 = categorical(T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_6);
T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_7 = categorical(T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_7);
T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_8 = categorical(T.DoHeadachesThatLastMoreThanTwoHoursHaveAnyOfTheFollowing_Plea_8);
T.HaveYouHadThisHeadache5OrMoreTimesInYourLife_ = categorical(T.HaveYouHadThisHeadache5OrMoreTimesInYourLife_);
T.WhenIsTheLastTimeYouHadOneOfTheseHeadaches_ = categorical(T.WhenIsTheLastTimeYouHadOneOfTheseHeadaches_);
T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_P = categorical(T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_P);
T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_1 = categorical(T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_1);
T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_2 = categorical(T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_2);
T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_3 = categorical(T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_3);
T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_4 = categorical(T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_4);
T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_5 = categorical(T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_5);
T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_6 = categorical(T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_6);
T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_7 = categorical(T.AroundTheTimeOfYourHeadaches_HaveYouEverSeenAnyOfTheFollowing_7);
T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFollow = categorical(T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFollow);
T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_1 = categorical(T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_1);
T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_2 = categorical(T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_2);
T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_3 = categorical(T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_3);
T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_4 = categorical(T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_4);
T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_5 = categorical(T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_5);
T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_6 = categorical(T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_6);
T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_7 = categorical(T.AroundTheTimeOfYourHeadDiscomfort_HaveYouEverSeenAnyOfTheFoll_7);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadach = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadach);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeada_1 = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeada_1);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeada_2 = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeada_2);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadDis = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadDis);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadD_1 = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadD_1);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadD_2 = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadD_2);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeada_3 = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeada_3);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeada_4 = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeada_4);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeada_5 = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeada_5);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeada_6 = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeada_6);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadD_3 = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadD_3);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadD_4 = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadD_4);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadD_5 = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadD_5);
T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadD_6 = categorical(T.HaveYouEverHadAnyOfTheFollowingHappenAroundTheTimeOfYourHeadD_6);
T.DoChangesInVision_Numbness_tingling_And_orDifficultySpeakingHap = categorical(T.DoChangesInVision_Numbness_tingling_And_orDifficultySpeakingHap);
T.HaveYouHadDifficultySpeakingWithYourHeadachesTwoOrMoreTimesInYo = categorical(T.HaveYouHadDifficultySpeakingWithYourHeadachesTwoOrMoreTimesInYo);
T.HaveYouHadDifficultySpeakingWithYourHeadDiscomfortTwoOrMoreTime = categorical(T.HaveYouHadDifficultySpeakingWithYourHeadDiscomfortTwoOrMoreTime);
T.WhenDoYouHaveDifficultySpeaking_PleaseMarkAllThatApply__choice_ = categorical(T.WhenDoYouHaveDifficultySpeaking_PleaseMarkAllThatApply__choice_);
T.WhenDoYouHaveDifficultySpeaking_PleaseMarkAllThatApply__choic_1 = categorical(T.WhenDoYouHaveDifficultySpeaking_PleaseMarkAllThatApply__choic_1);
T.WhenDoYouHaveDifficultySpeaking_PleaseMarkAllThatApply__choic_2 = categorical(T.WhenDoYouHaveDifficultySpeaking_PleaseMarkAllThatApply__choic_2);
T.WhenDoYouHaveDifficultySpeaking_PleaseMarkAllThatApply__choic_3 = categorical(T.WhenDoYouHaveDifficultySpeaking_PleaseMarkAllThatApply__choic_3);
T.WhenDoYouHaveDifficultySpeaking_PleaseMarkAllThatApply__choic_4 = categorical(T.WhenDoYouHaveDifficultySpeaking_PleaseMarkAllThatApply__choic_4);
T.WhenDoYouHaveDifficultySpeaking_PleaseMarkAllThatApply__choic_5 = categorical(T.WhenDoYouHaveDifficultySpeaking_PleaseMarkAllThatApply__choic_5);
T.WhenWasTheLastTimeYouHadDifficultySpeaking_ = categorical(T.WhenWasTheLastTimeYouHadDifficultySpeaking_);
T.HowLongDoesTheDifficultySpeakingUsuallyLast_ = categorical(T.HowLongDoesTheDifficultySpeakingUsuallyLast_);
T.DoesThisDifficultySpeakingEverLast5_60Minutes_ = categorical(T.DoesThisDifficultySpeakingEverLast5_60Minutes_);
T.HaveYouHadTheseVisionChangesWithYourHeadachesTwoOrMoreTimesInYo = categorical(T.HaveYouHadTheseVisionChangesWithYourHeadachesTwoOrMoreTimesInYo);
T.HaveYouHadTheseVisionChangesWithYourHeadDiscomfortTwoOrMoreTime = categorical(T.HaveYouHadTheseVisionChangesWithYourHeadDiscomfortTwoOrMoreTime);
T.WhenDoYouHaveTheseVisionChanges_PleaseMarkAllThatApply__choice_ = categorical(T.WhenDoYouHaveTheseVisionChanges_PleaseMarkAllThatApply__choice_);
T.WhenDoYouHaveTheseVisionChanges_PleaseMarkAllThatApply__choic_1 = categorical(T.WhenDoYouHaveTheseVisionChanges_PleaseMarkAllThatApply__choic_1);
T.WhenDoYouHaveTheseVisionChanges_PleaseMarkAllThatApply__choic_2 = categorical(T.WhenDoYouHaveTheseVisionChanges_PleaseMarkAllThatApply__choic_2);
T.WhenDoYouHaveTheseVisionChanges_PleaseMarkAllThatApply__choic_3 = categorical(T.WhenDoYouHaveTheseVisionChanges_PleaseMarkAllThatApply__choic_3);
T.WhenDoYouHaveTheseVisionChanges_PleaseMarkAllThatApply__choic_4 = categorical(T.WhenDoYouHaveTheseVisionChanges_PleaseMarkAllThatApply__choic_4);
T.WhenDoYouHaveTheseVisionChanges_PleaseMarkAllThatApply__choic_5 = categorical(T.WhenDoYouHaveTheseVisionChanges_PleaseMarkAllThatApply__choic_5);
T.WhenWasTheLastTimeYouHadTheseVisionChanges_ = categorical(T.WhenWasTheLastTimeYouHadTheseVisionChanges_);
T.HowLongDoTheseVisionChangesUsuallyLast_ = categorical(T.HowLongDoTheseVisionChangesUsuallyLast_);
T.DoTheseVisionChangesEverLast5_60Minutes_ = categorical(T.DoTheseVisionChangesEverLast5_60Minutes_);
T.AreTheVisionChangesOnlyOneOneSide_ = categorical(T.AreTheVisionChangesOnlyOneOneSide_);
T.DoTheVisionChangesSpreadOrMoveAcrossYourVision_ = categorical(T.DoTheVisionChangesSpreadOrMoveAcrossYourVision_);
T.HaveYouHadThisNumbnessAnd_orTinglingWithYourHeadachesTwoOrMoreT = categorical(T.HaveYouHadThisNumbnessAnd_orTinglingWithYourHeadachesTwoOrMoreT);
T.HaveYouHadThisNumbnessAnd_orTinglingWithYourHeadDiscomfortTwoOr = categorical(T.HaveYouHadThisNumbnessAnd_orTinglingWithYourHeadDiscomfortTwoOr);
T.WhenDoYouHaveThisNumbnessAnd_orTingling_PleaseMarkAllThatApply_ = categorical(T.WhenDoYouHaveThisNumbnessAnd_orTingling_PleaseMarkAllThatApply_);
T.WhenDoYouHaveThisNumbnessAnd_orTingling_PleaseMarkAllThatAppl_1 = categorical(T.WhenDoYouHaveThisNumbnessAnd_orTingling_PleaseMarkAllThatAppl_1);
T.WhenDoYouHaveThisNumbnessAnd_orTingling_PleaseMarkAllThatAppl_2 = categorical(T.WhenDoYouHaveThisNumbnessAnd_orTingling_PleaseMarkAllThatAppl_2);
T.WhenDoYouHaveThisNumbnessAnd_orTingling_PleaseMarkAllThatAppl_3 = categorical(T.WhenDoYouHaveThisNumbnessAnd_orTingling_PleaseMarkAllThatAppl_3);
T.WhenDoYouHaveThisNumbnessAnd_orTingling_PleaseMarkAllThatAppl_4 = categorical(T.WhenDoYouHaveThisNumbnessAnd_orTingling_PleaseMarkAllThatAppl_4);
T.WhenDoYouHaveThisNumbnessAnd_orTingling_PleaseMarkAllThatAppl_5 = categorical(T.WhenDoYouHaveThisNumbnessAnd_orTingling_PleaseMarkAllThatAppl_5);
T.WhenWasTheLastTimeYouHadThisNumbnessAnd_orTingling_ = categorical(T.WhenWasTheLastTimeYouHadThisNumbnessAnd_orTingling_);
T.HowLongDoesTheNumbnessAnd_orTinglingUsuallyLast_ = categorical(T.HowLongDoesTheNumbnessAnd_orTinglingUsuallyLast_);
T.DoesTheNumbnessAnd_orTinglingEverLast5_60Minutes_ = categorical(T.DoesTheNumbnessAnd_orTinglingEverLast5_60Minutes_);
T.IsTheNumbnessAnd_orTinglingOnlyOnOneSideOfYourBody_ = categorical(T.IsTheNumbnessAnd_orTinglingOnlyOnOneSideOfYourBody_);
T.DoesTheNumbnessAnd_orTinglingStartInOneSpot_AndThenSpreadOrMove = categorical(T.DoesTheNumbnessAnd_orTinglingStartInOneSpot_AndThenSpreadOrMove);
T.DoYouGetMotionSick_e_g_CarSick_NowOrWhenYouWereYounger_ = categorical(T.DoYouGetMotionSick_e_g_CarSick_NowOrWhenYouWereYounger_);
T.DoYourParents_Brothers_OrSistersGetMigraines_ = categorical(T.DoYourParents_Brothers_OrSistersGetMigraines_);
T.DuringYourHeadache_DoYouFeelAGreaterSenseOfGlareOrDazzleInYourE = categorical(T.DuringYourHeadache_DoYouFeelAGreaterSenseOfGlareOrDazzleInYourE);
T.DuringYourHeadDiscomfort_DoYouFeelAGreaterSenseOfGlareOrDazzleI = categorical(T.DuringYourHeadDiscomfort_DoYouFeelAGreaterSenseOfGlareOrDazzleI);
T.DoYouEverFeelAGreaterSenseOfGlareOrDazzleInYourEyesThanUsualByB = categorical(T.DoYouEverFeelAGreaterSenseOfGlareOrDazzleInYourEyesThanUsualByB);
T.DuringYourHeadDiscomfort_DoFlickeringLights_Glare_SpecificColor = categorical(T.DuringYourHeadDiscomfort_DoFlickeringLights_Glare_SpecificColor);
T.DuringYourHeadache_DoFlickeringLights_Glare_SpecificColors_OrHi = categorical(T.DuringYourHeadache_DoFlickeringLights_Glare_SpecificColors_OrHi);
T.DoFlickeringLights_Glare_SpecificColors_OrHighContrastStripedPa = categorical(T.DoFlickeringLights_Glare_SpecificColors_OrHighContrastStripedPa);
T.DuringYourHeadache_DoYouTurnOffTheLightsOrDrawACurtainToAvoidBr = categorical(T.DuringYourHeadache_DoYouTurnOffTheLightsOrDrawACurtainToAvoidBr);
T.DuringYourHeadDiscomfort_DoYouTurnOffTheLightsOrDrawACurtainToA = categorical(T.DuringYourHeadDiscomfort_DoYouTurnOffTheLightsOrDrawACurtainToA);
T.DoYouEverTurnOffTheLightsOrDrawACurtainToAvoidBrightConditions_ = categorical(T.DoYouEverTurnOffTheLightsOrDrawACurtainToAvoidBrightConditions_);
T.DuringYourHeadache_DoYouHaveToWearSunglassesEvenInNormalDayligh = categorical(T.DuringYourHeadache_DoYouHaveToWearSunglassesEvenInNormalDayligh);
T.DuringYourHeadDiscomfort_DoYouHaveToWearSunglassesEvenInNormalD = categorical(T.DuringYourHeadDiscomfort_DoYouHaveToWearSunglassesEvenInNormalD);
T.DoYouEverHaveToWearSunglassesEvenInNormalDaylight_ = categorical(T.DoYouEverHaveToWearSunglassesEvenInNormalDaylight_);
T.DuringYourHeadache_DoBrightLightsHurtYourEyes_ = categorical(T.DuringYourHeadache_DoBrightLightsHurtYourEyes_);
T.DuringYourHeadDiscomfort_DoBrightLightsHurtYourEyes_ = categorical(T.DuringYourHeadDiscomfort_DoBrightLightsHurtYourEyes_);
T.DoBrightLightsEverHurtYourEyes_ = categorical(T.DoBrightLightsEverHurtYourEyes_);
T.IsYourHeadacheWorsenedByBrightLights_ = categorical(T.IsYourHeadacheWorsenedByBrightLights_);
T.IsYourHeadDiscomfortWorsenedByBrightLights_ = categorical(T.IsYourHeadDiscomfortWorsenedByBrightLights_);
T.IsYourHeadacheTriggeredByBrightLights_ = categorical(T.IsYourHeadacheTriggeredByBrightLights_);
T.IsYourHeadDiscomfortTriggeredByBrightLights_ = categorical(T.IsYourHeadDiscomfortTriggeredByBrightLights_);
T.DoYouHaveAnyOfTheAboveSymptomsEvenDuringYourHeadache_freeInterv = categorical(T.DoYouHaveAnyOfTheAboveSymptomsEvenDuringYourHeadache_freeInterv);
T.DoYouHaveAnyOfTheAboveSymptomsEvenWhenYouDoNotHaveHeadDiscomfor = categorical(T.DoYouHaveAnyOfTheAboveSymptomsEvenWhenYouDoNotHaveHeadDiscomfor);



% Transpose the notesText for ease of subsequent display
notesText=notesText';

end % function