%% Questionnaire organization
% Analysis code for the Penn Online Evaluation of Migraine (POEM) adapted
% for children and adolescents, and run for data collected through CHOP redcap
%
% Description:
%   This routine loads the .csv files generated by Redcap that have the
%   results of the migraine diagnostic pathway.
%
%   Subsequent functions called from this main script are responsible for
%   pre-processing of the data fields and then implementing the headache
%   classification pathway.
%

%% Housekeeping
clear variables
close all

%% Set paths to data and output
dataDir = '/Users/pattersonc/OneDrive - Children''s Hospital of Philadelphia/Research/Minds Matter/Data/HAsubstudy/Forms/';
analysisDir = '/Users/pattersonc/OneDrive - Children''s Hospital of Philadelphia/Research/Minds Matter/analysis/HAsubstudy/Forms/';

% Set the output filenames
outputResultExcelName = fullfile(analysisDir, 'POEMpeds_v2.3_results.xlsx');
rawDataSheets = {'HeadacheSubstudy-PrelimDataAnalysisCP_DATA_LABELS_2024-05-21_1230.csv'};

% get the full path to thisDataSheet
thisDataSheetFileName = fullfile(dataDir, rawDataSheets{1});


%% Organize and analyze POEM results
[POEM] = poemAnalysis_preProcess_redcap(thisDataSheetFileName);

% classify headache based upon table T
diagnosisTable = poemAnalysis_classify_redcap2(POEM);
writetable(diagnosisTable,outputResultExcelName,'Range','A4','WriteRowNames',true)

%% Organize headache questions
[HA,MEDS,PCSI] = headacheQ_preProcess_redcap(thisDataSheetFileName);
