%% poemAnalysis_main
% Analysis code for the Penn Online Evaluation of Migraine (POEM) adapted
% for children (<18), and run for data collected through CHOP redcap
%
% Description:
%   This routine loads the .csv files generated by Redcap that have the
%   results of the migraine diagnostic pathway.
%
%   Subsequent functions called from this main script are responsible for
%   pre-processing of the data fields and then implementing the headache
%   classification pathway.
%

%% Housekeeping
clear variables
close all

%% Set paths to data and output
dataDir = '/Users/pattersonc/OneDrive - Children''s Hospital of Philadelphia/Research/K23/Data/Forms/';
analysisDir = '/Users/pattersonc/OneDrive - Children''s Hospital of Philadelphia/Research/K23/analysis/Forms/';

% Set the output filenames
outputResultExcelName=fullfile(analysisDir, 'POEMpeds_v2.3_results.xlsx');
rawDataSheets={'HeadacheSubstudy-POEMResults_DATA.csv'};

% get the full path to thisDataSheet
thisDataSheetFileName=fullfile(dataDir, rawDataSheets{1});


%% load and pre-process thisDataSheet, returning table "T"
[T, notesText] = poemAnalysis_preProcess_redcap(thisDataSheetFileName);


%% classify headache based upon table T
diagnosisTable = poemAnalysis_classify_redcap2( T );
writetable(diagnosisTable,outputResultExcelName,'Range','A4','WriteRowNames',true)