%% Questionnaire organization
% Analysis code for the Penn Online Evaluation of Migraine (POEM) adapted
% for children and adolescents, and run for data collected through CHOP redcap
%
% Description:
%   This routine loads the .csv files generated by Redcap that have the
%   results of the migraine diagnostic pathway.
%
%   Subsequent functions called from this main script are responsible for
%   pre-processing of the data fields and then implementing the headache
%   classification pathway.
%

%% Housekeeping
clc
clear variables
close all

addpath '/Users/pattersonc/Documents/MATLAB/commonFx'

%% Set paths to data and output
dataDir = '/Users/pattersonc/OneDrive - Children''s Hospital of Philadelphia/Research/Minds Matter/Data/HAsubstudy/Forms/';
analysisDir = '/Users/pattersonc/OneDrive - Children''s Hospital of Philadelphia/Research/Minds Matter/analysis/HAsubstudy/Forms/';

% Set the output filenames
outputResultExcelName = fullfile(analysisDir, 'microbiome_results.xlsx');
rawDataSheets = {'HeadacheSubstudy-MicrobiomeSamples_DATA_LABELS_2026-07-24_0900.csv'};

% get the full path to thisDataSheet
thisDataSheetFileName = fullfile(dataDir, rawDataSheets{1});


%% Organize and analyze POEM results
[T,FinalTable] = preProcess_microbiome(thisDataSheetFileName);

% classify headache based upon table T
diagnosisTable = poemAnalysis_classify_redcap2(T);

%% Determine diagnosis categories
DxCat = Dx_categoriesV2(T);


%% Save final table
FinalTable.preConcHAdx = diagnosisTable.HAdxSimp;
FinalTable.Outcome_prolongedPTH = DxCat.prolongedPTH;
FinalTable.Outcome_subcat = DxCat.category;
writetable(FinalTable,outputResultExcelName,'Range','A4','WriteRowNames',true)


%% Calculate CAMS
analysis_pathCAMS = getpref('assocSxHA','assocSxHaAnalysisPath');
load([analysis_pathCAMS '/CAMS_ChopAll_May2024.mat'],'CAMS','Chop_mdl')

var_HAaSx = CAMS.var_pres;

haASx = [T.othSx_nausea T.othSx_vomiting T.othSx_lightsens T.othSx_soundsens...
    T.othSx_smellsens T.othSx_lighthead T.othSx_spinning T.othSx_balance... 
    T.othSx_thinking T.vis_blurred T.vis_double T.othSx_ringing T.othSx_neckpain];

binary_hx = cell(size(haASx));
binary_struct = NaN*ones(size(haASx,2),1);
for x = 1:size(haASx,2)
    temp = haASx(:,x);
    outcome = unique(temp);
        for y = 1:size(haASx,1)
            binary_struct(x,:) = 2;
                switch temp(y)
                    case outcome(1)
                        binary_hx{y,x} = [1 0];
                    case outcome(2)
                        binary_hx{y,x} = [0 1];
                end
        end
end

% concatonate each subjects binary outcomes
binary_Hx = NaN*ones(size(binary_hx,1),size(var_HAaSx,1)*2);
temp = [];
for x = 1:size(binary_hx,1)
    for y = 1:size(binary_hx,2)
        temp = cat(2,temp,cell2mat(binary_hx(x,y)));
    end
    binary_Hx(x,:) = temp;
    temp = [];
end

CAMS_model = CAMS.MCA_model;

% Calculate CAMS scores
MCA_no=3;
MCA_score_HAaSx = NaN*ones(size(binary_Hx,1),MCA_no);
for x = 1:size(binary_Hx,1)
    for y = 1:MCA_no
        temp1 = binary_Hx(x,:);
        temp2 = CAMS_model(:,y);
        r=temp1*temp2;
        MCA_score_HAaSx(x,y) = r;
    end
end

T.CAMS1 = 1*MCA_score_HAaSx(:,1);
T.CAMS2 = 1*MCA_score_HAaSx(:,2);
T.CAMS3 = -1*MCA_score_HAaSx(:,3);

CAMS = runCAMS(Chop_mdl(:,16:28),CAMS.var_pres,CAMS.var_abs,'MCA_no',8,'xColor',0.6,'xBubble',80,'Sn',[1 1 -1]);
hold on
plot(mean(T.CAMS1_T1),mean(T.CAMS2_T1),'ok')

clear MCA* temp* x y r binary* haASx
